Sahi.prototype._click=function(a,b){this.checkNull(a,"_click");this.checkVisible(a);if(this.isApplet(a))return a.click();if(this.isFlexObj(a))return null!=this.lookInside&&(a=a.inside(this.lookInside)),a.click();this.markStepDone(this.currentStepId,this.currentType);this.simulateClick(a,!1,!1,b);try{a&&a.href&&0==a.href.indexOf("mailto:")&&window.setTimeout("_sahi.loaded\x3dtrue",10)}catch(c){}};
Sahi.prototype._doubleClick=function(a,b){this.checkNull(a,"_doubleClick");this.checkVisible(a);if(this.isFlexObj(a))return null!=this.lookInside&&(a=a.inside(this.lookInside)),a.doubleClick();this.simulateDoubleClick(a,!1,!0,b)};Sahi.prototype._rightClick=function(a,b){this.checkNull(a,"_rightClick");this.checkVisible(a);if(this.isFlexObj(a))return null!=this.lookInside&&(a=a.inside(this.lookInside)),a.rightClick();this.simulateRightClick(a,!0,!1,b)};
Sahi.prototype.isMsPointerEventsEnabled=function(){return window.navigator.msPointerEnabled&&!this._isIE11Plus()};
Sahi.prototype._mouseOver=function(a,b){null!=this.lookInside&&(a=a.inside(this.lookInside));this.checkNull(a,"_mouseOver");this.checkVisible(a);if(this.isFlexObj(a))return null!=this.lookInside&&(a=a.inside(this.lookInside)),a.mouseOver();var c=window.navigator.pointerEnabled,d=this.isMsPointerEventsEnabled();c&&this.simulateMouseEvent(a,"pointermove",!1,!1,b);d&&this.simulateMouseEvent(a,"MSPointerMove",!1,!1,b);this.simulateMouseEvent(a,"mousemove",!1,!1,b);c&&this.simulateMouseEvent(a,"pointerover",
!1,!1,b);d&&this.simulateMouseEvent(a,"MSPointerOver",!1,!1,b);this.simulateMouseEvent(a,"mouseover",!1,!1,b);this.setLastBlurFn(function(){try{c&&_sahi.simulateMouseEvent(a,"pointermove"),d&&_sahi.simulateMouseEvent(a,"MSPointerMove"),_sahi.simulateMouseEvent(a,"mousemove"),c&&_sahi.simulateMouseEvent(a,"pointerout"),d&&_sahi.simulateMouseEvent(a,"MSPointerOut"),_sahi.simulateMouseEvent(a,"mouseout"),_sahi.simulateMouseEvent(a,"blur")}catch(b){}})};
Sahi.prototype._mouseDown=function(a,b,c){if(this.isFlexObj(a))return null!=this.lookInside&&(a=a.inside(this.lookInside)),a.mouseDown();var d=window.navigator.pointerEnabled,e=this.isMsPointerEventsEnabled();d&&this.simulateMouseEvent(a,"pointerdown",b,!1,c);e&&this.simulateMouseEvent(a,"MSPointerDown",b,!1,c);this.simulateMouseEvent(a,"mousedown",b,!1,c)};
Sahi.prototype._mouseUp=function(a,b,c){if(this.isFlexObj(a))return null!=this.lookInside&&(a=a.inside(this.lookInside)),a.mouseUp();var d=window.navigator.pointerEnabled,e=this.isMsPointerEventsEnabled();d&&this.simulateMouseEvent(a,"pointerup",b,!1,c);e&&this.simulateMouseEvent(a,"MSPointerUp",b,!1,c);this.simulateMouseEvent(a,"mouseup",b,!1,c)};Sahi.prototype._keyPress=function(a,b,c){var d=this.shouldAppend(a);this.simulateKeyPressEvents(a,b,c,d)};
Sahi.prototype.simulateKeyPressEvents=function(a,b,c,d){var e=a.value,f=0,h=0,k=null;"number"==typeof b?(h=b,f=this.getKeyCode(h),k=String.fromCharCode(h)):"object"==typeof b?(f=b[0],h=b[1],k=String.fromCharCode(h)):"string"==typeof b&&(h=b.charCodeAt(0),f=this.getKeyCode(h),k=b);(b=65<=h&&90>=h)&&(c=""+c+"|SHIFT|");this.simulateKeyEvent([b?16:f,0],a,"keydown",c);this.isSafariLike()?this.simulateKeyEvent([f,h],a,"keypress",c):this.simulateKeyEvent([0,h],a,"keypress",c);d&&10!=h&&e==a.value&&(!this._isFF4Plus()||
this._isFF4Plus()&&"CTRL"!=c&&"ALT"!=c)&&(this.isEditableFormElement(a)?a.value+=k:a.isContentEditable&&(a.innerHTML+=k));try{this._isIE()&&!this._isIE9PlusStrictMode()||this.simulateKeyEvent([f,0],a,"input",c)}catch(l){}this.simulateKeyEvent([f,0],a,"keyup",c)};
Sahi.prototype.replaceSelectedText=function(a){var b,c;window.getSelection?(b=window.getSelection(),b.rangeCount&&(c=b.getRangeAt(0),c.deleteContents(),a=document.createTextNode(a),c.insertNode(a),b.removeAllRanges(),c.selectNodeContents(a),c.collapse(),b.addRange(c))):document.selection&&document.selection.createRange&&(c=document.selection.createRange(),c.text=a)};
Sahi.prototype._keyPressEvent=function(a,b,c){this.checkNull(a,"_keyPressEvent",1);this.checkVisible(a);this.simulateKeyEvent("object"==typeof b?b:[0,b],a,"keypress",c)};Sahi.prototype._focus=function(a){this.isFlexObj(a)&&null!=this.lookInside&&(a=a.inside(this.lookInside));try{a.focus()}catch(b){}this.simulateEvent(a,"focus")};Sahi.prototype._blur=function(a){this.simulateEvent(a,"blur")};Sahi.prototype._removeFocus=Sahi.prototype._blur;
Sahi.prototype._keyDown=function(a,b,c){this.checkNull(a,"_keyDown",1);this.checkVisible(a);this.simulateKeyEvent("number"==typeof b?[b,0]:b,a,"keydown",c)};Sahi.prototype._keyUp=function(a,b,c){this.checkNull(a,"_keyUp",1);this.checkVisible(a);this.simulateKeyEvent("number"==typeof b?[b,0]:b,a,"keyup",c)};Sahi.prototype._closeWindow=function(a){if(!a)try{a=this.absoluteTop().window}catch(b){a=window}a&&(a.open("","_self"),a.close())};
Sahi.prototype.isCheckboxRadioSimulationRequired=function(){return this._isChrome()?42<this.getChromeVersion()?!1:this.chromeExplicitCheckboxRadioToggle:this.isSafariLike()&&!this._isEdge()};
Sahi.prototype.simulateDoubleClick=function(a,b,c,d){var e=!0,f=window.navigator.pointerEnabled,h=this.isMsPointerEventsEnabled();this._isFF()||this.isSafariLike()||this._isOpera()?(this.simulateMouseEvent(a,"mousemove"),this.simulateMouseEvent(a,"mouseover"),this.simulateMouseEvent(a,"mousedown",b,!1,d),this.invokeLastBlur(),(e=this.isFocusableFormElement(a))&&this.simulateEvent(a,"focus"),this.simulateMouseEvent(a,"mouseup",b,!1,d),this.simulateMouseEvent(a,"click",b,!1,d),this.simulateMouseEvent(a,
"mousedown",b,c,d),this.simulateMouseEvent(a,"mouseup",b,c,d),this.simulateMouseEvent(a,"click",b,c,d),this.simulateMouseEvent(a,"dblclick",b,c,d)):this._isIE()&&!this._isIE9PlusStrictMode()?(f&&this.simulateMouseEvent(a,"pointermove"),h&&this.simulateMouseEvent(a,"MSPointerMove"),this.simulateMouseEvent(a,"mousemove"),f&&this.simulateMouseEvent(a,"pointerover"),h&&this.simulateMouseEvent(a,"MSPointerOver"),this.simulateMouseEvent(a,"mouseover"),f&&this.simulateMouseEvent(a,"pointerdown",b,!1,d),
h&&this.simulateMouseEvent(a,"MSPointerDown",b,!1,d),this.simulateMouseEvent(a,"mousedown",b,!1,d),this.invokeLastBlur(),this._isIE()&&this.simulateEvent(a,"focusin"),this.simulateMouseEvent(a,"focus"),f&&this.simulateMouseEvent(a,"pointerup",b,!1,d),h&&this.simulateMouseEvent(a,"MSPointerUp",b,!1,d),this.simulateMouseEvent(a,"mouseup",b,!1,d),this.simulateMouseEvent(a,"click",b,!1,d),f&&this.simulateMouseEvent(a,"pointerup",b,!1,d),h&&this.simulateMouseEvent(a,"MSPointerUp",b,!1,d),this.simulateMouseEvent(a,
"mouseup",b,!1,d),this.simulateMouseEvent(a,"dblclick",b,c,d)):this._isIE9PlusStrictMode()&&(f&&this.simulateMouseEvent(a,"pointermove"),h&&this.simulateMouseEvent(a,"MSPointerMove"),this.simulateMouseEvent(a,"mousemove"),f&&this.simulateMouseEvent(a,"pointerover"),h&&this.simulateMouseEvent(a,"MSPointerOver"),this.simulateMouseEvent(a,"mouseover"),f&&this.simulateMouseEvent(a,"pointerdown",b,!1,d),h&&this.simulateMouseEvent(a,"MSPointerDown",b,!1,d),this.simulateMouseEvent(a,"mousedown",b,!1,d),
this.invokeLastBlur(),this._isIE11Plus()&&(this.simulateEvent(a,"beforeactivate"),this.simulateEvent(a,"activate")),this._isIE()&&this.simulateEvent(a,"focusin"),this.simulateMouseEvent(a,"focus"),f&&this.simulateMouseEvent(a,"pointerup",b,!1,d),h&&this.simulateMouseEvent(a,"MSPointerUp",b,!1,d),this.simulateMouseEvent(a,"mouseup",b,!1,d),this.simulateMouseEvent(a,"click",b,!1,d),f&&this.simulateMouseEvent(a,"pointerdown",b,c,d),h&&this.simulateMouseEvent(a,"MSPointerDown",b,c,d),this.simulateMouseEvent(a,
"mousedown",b,c,d),f&&this.simulateMouseEvent(a,"pointerup",b,c,d),h&&this.simulateMouseEvent(a,"MSPointerUp",b,c,d),this.simulateMouseEvent(a,"mouseup",b,c,d),this.simulateMouseEvent(a,"click",b,c,d),this.simulateMouseEvent(a,"dblclick",b,c,d),this._isIE11Plus()&&this.simulateEvent(a,"deactivate"));e&&this.setLastBlurFn(function(){try{f&&_sahi.simulateMouseEvent(a,"pointermove"),h&&_sahi.simulateMouseEvent(a,"MSPointerMove"),_sahi.simulateMouseEvent(a,"mousemove"),f&&_sahi.simulateMouseEvent(a,"pointerout"),
h&&_sahi.simulateMouseEvent(a,"MSPointerOut"),_sahi.simulateMouseEvent(a,"mouseout"),_sahi._isFF()||_sahi._isIE9PlusStrictMode()||_sahi._isOpera()||"checkbox"!=a.type&&"radio"!=a.type||_sahi.simulateEvent(a,"change"),_sahi._isIE()&&_sahi.simulateEvent(a,"focusout"),_sahi.simulateEvent(a,"blur")}catch(b){}})};
Sahi.prototype.simulateRightClick=function(a,b,c,d){c=!0;var e=window.navigator.pointerEnabled,f=this.isMsPointerEventsEnabled();this._isFF()||this.isSafariLike()||this._isOpera()?(this.simulateMouseEvent(a,"mousemove"),this.simulateMouseEvent(a,"mouseover"),this.simulateMouseEvent(a,"mousedown",b,!1,d),this.invokeLastBlur(),(c=this.isFocusableFormElement(a))&&this.simulateEvent(a,"focus"),this.simulateMouseEvent(a,"mouseup",b,!1,d),this.simulateMouseEvent(a,"contextmenu",b,!1,d)):this._isIE()&&(e&&
this.simulateMouseEvent(a,"pointermove"),f&&this.simulateMouseEvent(a,"MSPointerMove"),this.simulateMouseEvent(a,"mousemove"),e&&this.simulateMouseEvent(a,"pointerover"),f&&this.simulateMouseEvent(a,"MSPointerOver"),this.simulateMouseEvent(a,"mouseover"),e&&this.simulateMouseEvent(a,"pointerdown",b,!1,d),f&&this.simulateMouseEvent(a,"MSPointerDown",b,!1,d),this.simulateMouseEvent(a,"mousedown",b,!1,d),this.invokeLastBlur(),this._isIE11Plus()&&(this.simulateEvent(a,"beforeactivate"),this.simulateEvent(a,
"activate")),this.simulateEvent(a,"focusin"),this.simulateMouseEvent(a,"focus"),e&&this.simulateMouseEvent(a,"pointerup",b,!1,d),f&&this.simulateMouseEvent(a,"MSPointerUp",b,!1,d),this.simulateMouseEvent(a,"mouseup",b,!1,d),this.simulateMouseEvent(a,"contextmenu",b,!1,d),this._isIE11Plus()&&this.simulateEvent(a,"deactivate"));c&&this.setLastBlurFn(function(){try{e&&_sahi.simulateMouseEvent(a,"pointermove"),f&&_sahi.simulateMouseEvent(a,"MSPointerMove"),_sahi.simulateMouseEvent(a,"mousemove"),e&&_sahi.simulateMouseEvent(a,
"pointerout"),f&&_sahi.simulateMouseEvent(a,"MSPointerOut"),_sahi.simulateMouseEvent(a,"mouseout"),_sahi._isFF()||_sahi._isIE9PlusStrictMode()||_sahi._isOpera()||"checkbox"!=a.type&&"radio"!=a.type||_sahi.simulateEvent(a,"change"),_sahi._isIE()&&_sahi.simulateEvent(a,"focusout"),_sahi.simulateEvent(a,"blur")}catch(b){}})};Sahi.prototype.isFocusableFormElement=function(a){return!this.isFormElement(a)||this.isSafariLike()&&("checkbox"==a.type||"radio"==a.type||"button"==a.type)?!1:!0};
Sahi.prototype.downloadFromBlobUrl=function(a,b){var c=this.createRequestObject();c.open("GET",a,!0);c.responseType="blob";c.onload=function(){blob=c.response;_sahi.sendToServerBlob("/_s_/dyn/Player_handelBrowserBlobObject?fileName\x3d"+b,blob,!0)};c.send()};
Sahi.prototype.simulateClick=function(a,b,c,d){var e=this.getEncapsulatingLink(a),f=""+e;if(0==f.indexOf("blob:")){var h=e.download;if(""!=h){this.downloadFromBlobUrl(f,h);return}}if(null!=e&&this._isFF()){e.__sahi__prevClick=e.onclick;var k=this.getWindow(e);e.onclick=function(a){return _sahi.wrap(_sahi.linkClick)(a?a:k.event)}}var l=window.navigator.pointerEnabled,g=this.isMsPointerEventsEnabled();l&&this.simulateMouseEvent(a,"pointermove");g&&this.simulateMouseEvent(a,"MSPointerMove");this.simulateMouseEvent(a,
"mousemove");l&&this.simulateMouseEvent(a,"pointerover");g&&this.simulateMouseEvent(a,"MSPointerOver");this.simulateMouseEvent(a,"mouseover");l&&this.simulateMouseEvent(a,"pointerdown",b,!1,d);g&&this.simulateMouseEvent(a,"MSPointerDown",b,!1,d);this.simulateMouseEvent(a,"mousedown",b,!1,d);this.invokeLastBlur();this._isIE11Plus()&&(this.simulateEvent(a,"beforeactivate"),this.simulateEvent(a,"activate"));if(f=this.isFocusableFormElement(a))this._isIE()&&this.simulateEvent(a,"focusin"),this.simulateEvent(a,
"focus");l&&this.simulateMouseEvent(a,"pointerup",b,!1,d);g&&this.simulateMouseEvent(a,"MSPointerUp",b,!1,d);this.simulateMouseEvent(a,"mouseup",b,!1,d);try{this._isIE()&&a&&(this.areTagNamesEqual(a.tagName,"LABEL")||null!=e||a.type&&("submit"==a.type||"reset"==a.type||"image"==a.type||"checkbox"==a.type||"radio"==a.type))?(null!=e&&this.markStepDone(this.currentStepId,this.currentType),a.click()):window.opera?(this.simulateMouseEvent(a,"click",b,c,d),!this.areTagNamesEqual(a.tagName,"INPUT")||"radio"!=
a.type&&"checkbox"!=a.type||this.simulateEvent(a,"change")):(h=!1,this.isCheckboxRadioSimulationRequired()&&this.areTagNamesEqual(a.tagName,"INPUT")&&("radio"==a.type||"checkbox"==a.type)&&(h=!0,a.checked="radio"==a.type?!0:!a.checked,this.simulateEvent(a,"change"),this.simulateMouseEvent(a,"click",b,c,d)),h||this.simulateMouseEvent(a,"click",b,c,d))}catch(m){}this._isIE11Plus()&&this.simulateEvent(a,"deactivate");f&&this.setLastBlurFn(function(){try{l&&_sahi.simulateMouseEvent(a,"pointermove"),g&&
_sahi.simulateMouseEvent(a,"MSPointerMove"),_sahi.simulateMouseEvent(a,"mousemove"),l&&_sahi.simulateMouseEvent(a,"pointerout"),g&&_sahi.simulateMouseEvent(a,"MSPointerOut"),_sahi.simulateMouseEvent(a,"mouseout"),_sahi._isFF()||_sahi._isIE9PlusStrictMode()||_sahi._isOpera()||"checkbox"!=a.type&&"radio"!=a.type||_sahi.simulateEvent(a,"change"),_sahi._isIE()&&_sahi.simulateEvent(a,"focusout"),_sahi.simulateEvent(a,"blur")}catch(b){}});null!=e&&this._isFF()&&(e.onclick=e.__sahi__prevClick)};
Sahi.prototype.simulateMouseEvent=function(a,b,c,d,e){var f=this.findClientPosWithOffset(a);this.simulateMouseEventXY(a,b,f[0],f[1],c,d,e)};Sahi.prototype.simulateDragEvent=function(a,b,c,d){var e=this.findClientPosWithOffset(a);this.simulateDragEventXY(a,b,e[0],e[1],c,d)};
Sahi.prototype.simulateDragEventXY=function(a,b,c,d,e,f){f||(f="");var h=-1!=f.indexOf("SHIFT"),k=-1!=f.indexOf("CTRL"),l=-1!=f.indexOf("ALT");f=-1!=f.indexOf("META");if(this._isIE()&&!this._isIE11Plus()){var g=a.ownerDocument.createEventObject();g.clientX=c;g.clientY=d;g.ctrlKey=k;g.altKey=l;g.metaKey=f;g.shiftKey=h;if("pointerdown"==b||"pointerup"==b||"pointermove"==b||"MSPointerDown"==b||"MSPointerUp"==b||"MSPointerMove"==b||"mousedown"==b||"mouseup"==b||"mousemove"==b)g.button=1;a.fireEvent(this.getEventTypeName(b),
g);g.cancelBubble=!0}else if(this._isFF())g=a.ownerDocument.createEvent("DragEvents"),g.initDragEvent(b,!0,!0,a.ownerDocument.defaultView,1,c,d,c,d,k,l,h,f,0,null,30<=this._getFFVersion()?null:e),a.dispatchEvent(g);else if(this._isChrome()||this._isIE11Plus())g=a.ownerDocument.createEvent("HTMLEvents"),g.initEvent(b,!0,!0,a.ownerDocument.defaultView,1,c,d,c,d,k,l,h,f,0,null),g.dataTransfer=e,a.dispatchEvent(g)};
Sahi.prototype.simulateMouseEventXY=function(a,b,c,d,e,f,h){h||(h="");var k=-1!=h.indexOf("SHIFT"),l=-1!=h.indexOf("CTRL"),g=-1!=h.indexOf("ALT");h=-1!=h.indexOf("META");this._isIE()&&(!this._isIE9PlusStrictMode()||"click"==b&&f)||(this.isSafariLike()||this._isIE9PlusStrictMode()||this._isOpera()?a.ownerDocument.createEvent&&(this._isChrome()&&42<this.getChromeVersion()?this.simulateViaMouseEventConstructor(a,b,c,d,e,f,k,l,g,h):this.simulateMouseViaHTMLEvents(a,b,c,d,e,f,k,l,g,h)):11>this._getFFVersion()?
this.simulateViaInitMouseEvent(a,b,c,d,e,f,k,l,g,h):this.simulateViaMouseEventConstructor(a,b,c,d,e,f,k,l,g,h));if(this.checkForDuplicateEventsOnIE9Plus(a,b)&&!this._isIE11Plus()){f=a.ownerDocument.createEventObject();f.clientX=c+this.getScrollOffsetX();f.clientY=d+this.getScrollOffsetY();f.ctrlKey=l;f.altKey=g;f.metaKey=h;f.shiftKey=k;if("pointerdown"==b||"pointerup"==b||"pointermove"==b||"MSPointerDown"==b||"MSPointerUp"==b||"MSPointerMove"==b||"mousedown"==b||"mouseup"==b||"mousemove"==b)f.button=
e?2:1;a.fireEvent(this.getEventTypeName(b),f);f.cancelBubble=!0}};Sahi.prototype.simulateViaMouseEventConstructor=function(a,b,c,d,e,f,h,k,l,g){var m=0;"mousedown"==b&&(m=e?2:1);f=f?2:1;this._isChrome()&&"contextmenu"==b&&(f=0);b=new MouseEvent(b,{bubbles:!0,cancelable:!0,view:a.ownerDocument.defaultView.window,detail:f,screenX:c+this.getScrollOffsetX(),screenY:d+this.getScrollOffsetY(),clientX:c,clientY:d,ctrlKey:k,altKey:l,shiftKey:h,metaKey:g,button:e?2:0,buttons:m});a.dispatchEvent(b)};
Sahi.prototype.simulateViaInitMouseEvent=function(a,b,c,d,e,f,h,k,l,g){var m=a.ownerDocument.createEvent("MouseEvents");m.initMouseEvent(b,!0,!0,a.ownerDocument.defaultView.window,f?2:1,c+this.getScrollOffsetX(),d+this.getScrollOffsetY(),c,d,k,l,h,g,e?2:0,null);a.dispatchEvent(m)};
Sahi.prototype.simulateMouseViaHTMLEvents=function(a,b,c,d,e,f,h,k,l,g){var m=0;"mousedown"==b&&(m=e?2:1);var n=a.ownerDocument.createEvent("HTMLEvents");n.initEvent(b,!0,!0);n.clientX=c;n.clientY=d;n.pageX=c+this.getScrollOffsetX();n.pageY=d+this.getScrollOffsetY();n.screenX=c;n.screenY=d;n.button=e?2:0;n.which=e?3:1;n.detail=f?2:"contextmenu"==b?0:1;n.ctrlKey=k;n.altKey=l;n.metaKey=g;n.shiftKey=h;-1!=b.toLowerCase().indexOf("pointer")&&(n.pointerId=1,n.isPrimary=!0,n.buttons=m);a.dispatchEvent(n)};
Sahi.prototype.checkForDuplicateEventsOnIE9Plus=function(a,b){return this._isIE()?this._isIE9Plus()?null==a["on"+b]||null!=a["on"+b]&&!this._isIE9PlusStrictMode():!0:!1};Sahi.pointTimer=0;
Sahi.prototype._highlight=function(a){if(this.isFlexObj(a))return null!=this.lookInside&&(a=a.inside(this.lookInside)),a.highlight();if(this.isApplet(a))return a.highlight();Sahi.lastUnhighlight&&(Sahi.lastUnhighlight(),window.clearTimeout(Sahi.unhighlightTimer));var b=a.style.border,c=a.style.outline;a.style.border="1px solid red";a.style.outline="1px solid red";Sahi.lastUnhighlight=function(){a.style.border=b;a.style.outline=c;Sahi.lastUnhighlight=null};Sahi.unhighlightTimer=window.setTimeout(Sahi.lastUnhighlight,
1E3)};
Sahi.prototype.navigateLink=function(){var a=this.lastLink;if(!(!a||this.lastLinkEvent.getPreventDefault&&this.lastLinkEvent.getPreventDefault()||(this._isIE()||this.isSafariLike())&&!1==this.lastLinkEvent.returnValue)){var b=this.getWindow(a);if(0==a.href.indexOf("javascript:"))a=a.href.substring(11),b.setTimeout(unescape(a),0);else{var c=a.target;if(null==a.target||""==a.target)if(c=this.getBaseTarget(b),null==c||""==c)c="_self";var d=this.getNamedWindow(b,c);if(d){if(this.isSafariLike())try{d._sahi.onBeforeUnLoad()}catch(e){}d.location=a.href}else b.open(a.href,
c)}}};Sahi.prototype._type=function(a,b){for(var c=this.shouldAppend(a),d=0;d<b.length;d++)this.simulateKeyPressEvents(a,b.charAt(d),null,c)};Sahi.prototype._setValue=function(a,b){if(null!=b){if(this.isApplet(a))return a.setValue(b);if(this.isFlexObj(a))return null!=this.lookInside&&(a=a.inside(this.lookInside)),a.setValue(b);this.invokeLastBlur();this.setValue(a,b)}};
Sahi.prototype.shouldAppend=function(a){return a&&(a.isContentEditable||a.type&&-1!=this.findInArray(this.textboxTypes,a.type))&&!(this._isFF()&&!this._isFF4Plus()&&!this._isHTMLUnit()||a.readOnly||a.disabled)};
Sahi.prototype.setValue=function(a,b){this.checkNull(a,"_setValue",1);this.checkVisible(a);if(this._isIE()){try{a.setActive()}catch(c){}this.simulateEvent(a,"focusin")}this.simulateEvent(a,"focus");b=""+b;var d=this.navigator.userAgent.toLowerCase();if(-1!=d.indexOf("windows")){if(b=b.replace(/\r/g,""),!this._isFF()||12<=this._getFFVersion())b=b.replace(/\n/g,"\r\n")}else d.indexOf("macintosh")?(b=b.replace(/\r\n/g,"\r"),b=b.replace(/\n/g,"\r")):-1!=d.indexOf("linux")&&(b=b.replace(/\r\n/g,"\n"),
b=b.replace(/\r/g,"\n"));d=a.value;this._isFF4Plus()&&this._focus(a);if(a.type&&"hidden"==a.type)a.value=b;else{if(a.type&&("range"==a.type||"date"==a.type||"number"==a.type))a.value=b;else if(!a.type||-1==a.type.indexOf("select")){var e=this.shouldAppend(a);this.isEditableFormElement(a)&&(a.value="");if("string"==typeof b){var f=b.length;a.maxLength&&0<=a.maxLength&&b.length>a.maxLength&&(f=a.maxLength);for(var h=0;h<f;h++){var k=b.charAt(h);this.simulateKeyPressEvents(a,k,null,e)}}}var l=d!=b;this.setLastBlurFn(function(){try{l&&
(_sahi._isFF3()||_sahi.simulateEvent(a,"change")),_sahi._isIE()&&(_sahi.simulateEvent(a,"deactivate"),_sahi.simulateEvent(a,"focusout")),_sahi._isIE()&&a.blur(),_sahi.simulateEvent(a,"blur"),_sahi._isIE()||_sahi.simulateEvent(a,"focusout")}catch(b){}})}};
Sahi.prototype._setFile2=function(a,b,c){this._setFile(a,b,c);this._isIE()?(a.outerHTML=a.outerHTML.replace(/type=['"]?file['"]?/,"type\x3dtext"),c=a.name,""==c&&(c=a.id),""!=c&&(a=this._textbox(c),this._setValue(a,b),this._blur(a))):(a.type="text",this._setValue(a,b),this._blur(a))};
Sahi.prototype._setFile=function(a,b,c){if(null!=b){if(!c&&((c=!a.form||this.isBlankOrNull(a.form.action)||"string"!=typeof a.form.action?this.getWindow(a).location.href:a.form.action)&&-1!=(q=c.indexOf("?"))&&(c=c.substring(0,q)),0!=c.indexOf("http"))){var d=window.location;0==c.indexOf("/")?c=d.protocol+"//"+d.hostname+(d.port?":"+d.port:"")+c:(d=d.href,c=d.substring(0,d.lastIndexOf("/")+1)+c)}a=this._callServer("FileUpload_setFile","n\x3d"+a.name+"\x26v\x3d"+this.encode(b)+"\x26action\x3d"+this.encode(c));
if("true"!=a)throw Error(a);}};Sahi.prototype.simulateEvent=function(a,b){var c=!this._isIE()||this._isIE9StrictMode()||this._isIE11Plus(),d=this._isIE()&&!this._isIE11Plus();if(c){c={};c.type=b;c.button=0;c.bubbles=!0;c.cancelable=!0;if(!a)return;var e=a.ownerDocument.createEvent("HTMLEvents");e.initEvent(c.type,c.bubbles,c.cancelable);a.dispatchEvent(e)}d&&(c=a.ownerDocument.createEventObject(),c.type=b,c.bubbles=!0,c.cancelable=!0,c.cancelBubble=!0,a.fireEvent(this.getEventTypeName(b),c))};
Sahi.prototype.getKeyCode=function(a){return 97<=a&&122>=a?a-32:a};
Sahi.prototype.simulateKeyEvent=function(a,b,c,d){var e=a[0];a=a[1];d||(d="");var f=-1!=d.indexOf("SHIFT"),h=-1!=d.indexOf("CTRL"),k=-1!=d.indexOf("ALT");d=-1!=d.indexOf("META");if(!this._isIE()||this._isIE9PlusStrictMode())if(this.isSafariLike()||window.opera||this._isIE9PlusStrictMode()){if(b.ownerDocument.createEvent){var l=b.ownerDocument.createEvent("HTMLEvents"),g=l;window.opera||(g.bubbles=!0,g.cancelable=!0);g.ctrlKey=h;g.altKey=k;g.metaKey=d;g.charCode=a;g.keyCode="keypress"==c?a:e;g.shiftKey=
f;g.which=g.keyCode;g.detail=0;g.view=b.ownerDocument.defaultView;g.initEvent(c,!0,!0);b.dispatchEvent(g)}}else{g={};g.type=c;g.bubbles=!0;g.cancelable=!0;g.ctrlKey=h;g.altKey=k;g.metaKey=d;g.keyCode=e;g.charCode=a;g.shiftKey=f;if(!b)return;l=b.ownerDocument.createEvent("KeyEvents");l.initKeyEvent(g.type,g.bubbles,g.cancelable,b.ownerDocument.defaultView.window,g.ctrlKey,g.altKey,g.shiftKey,g.metaKey,g.keyCode,g.charCode);b.dispatchEvent(l)}this._isIE()&&!this._isIE11Plus()&&(g=b.ownerDocument.createEventObject(),
g.type=c,g.bubbles=!0,g.cancelable=!0,l=this.findClientPosWithOffset(b),g.clientX=l[0],g.clientY=l[1],g.ctrlKey=h,g.altKey=k,g.metaKey=d,g.keyCode=this._isIE()&&"keypress"==c?a:e,g.shiftKey=f,g.shiftLeft=f,g.cancelBubble=!0,g.target=b,b.fireEvent(this.getEventTypeName(c),g))};Sahi.prototype.getEventTypeName=function(a){return"object"==typeof MooTools?a:"on"+a};Sahi.prototype.typeNativePhantomJS=function(a){"function"===typeof window.callPhantom&&window.callPhantom(a)};
Sahi.prototype.clickNativePhantomJS=function(a,b,c,d){if("function"===typeof window.callPhantom){var e=this._position(a);a=this.getWindow(a);a=_sahi.computeFrameOffset(a);_sahi.debug(e[0]);_sahi.debug(e[1]);e[0]+=a[0];e[1]+=a[1];_sahi.debug(e[0]);_sahi.debug(e[1]);window.callPhantom(e,b,c,d)}};Sahi.prototype.dragDropNativePhantomJS=function(a,b){if("function"===typeof window.callPhantom){var c=this._position(a),d=this._position(b);window.callPhantom(c,d)}};Sahi.prototype._simulateMouseEvent=Sahi.prototype.simulateMouseEvent;
Sahi.prototype._simulateMouseEventXY=Sahi.prototype.simulateMouseEventXY;Sahi.prototype._simulateKeyEvent=Sahi.prototype.simulateKeyEvent;
Sahi.prototype.selectOption=function(a,b,c){c=c?"CTRL":null;var d=this._option(b,this._in(a));if(!d)throw Error("Option not found: "+b);if(this._isIE()){b=window.navigator.pointerEnabled;var e=this.isMsPointerEventsEnabled();b&&this.simulateMouseEvent(a,"pointerdown",!1,!1,c);e&&this.simulateMouseEvent(a,"MSPointerDown",!1,!1,c);this.simulateMouseEvent(a,"mousedown",!1,!1,c);b&&this.simulateMouseEvent(a,"pointerup",!1,!1,c);e&&this.simulateMouseEvent(a,"MSPointerUp",!1,!1,c);this.simulateMouseEvent(a,
"mouseup",!1,!1,c);d.selected=!0;this.simulateMouseEvent(a,"change");this.simulateMouseEvent(a,"click",!1,!1,c)}else this._isFF()?(d.selected=!0,this.simulateMouseEvent(d,"mousedown",!1,!1,c),this.simulateMouseEvent(d,"mouseup",!1,!1,c),this.simulateMouseEvent(a,"change"),this.simulateMouseEvent(d,"click",!1,!1,c)):(d.selected=!0,this.simulateMouseEvent(a,"change"))};
Sahi.prototype.selectOptionWithSize=function(a,b,c){c=c?"CTRL":null;var d=this._option(b,this._in(a));if(!d)throw Error("Option not found: "+b);if(this._isIE()){b=window.navigator.pointerEnabled;var e=this.isMsPointerEventsEnabled();b&&this.simulateMouseEvent(a,"pointerdown",!1,!1,c);e&&this.simulateMouseEvent(a,"MSPointerDown",!1,!1,c);this.simulateMouseEvent(a,"mousedown",!1,!1,c);this.simulateEvent(a,"beforeactivate");this.simulateEvent(a,"activate");this.simulateEvent(a,"focusin");this.simulateEvent(a,
"focus");b&&this.simulateMouseEvent(a,"pointerup",!1,!1,c);e&&this.simulateMouseEvent(a,"MSPointerUp",!1,!1,c);this.simulateMouseEvent(a,"mouseup",!1,!1,c);d.selected=!0;this.simulateMouseEvent(a,"change");this.simulateMouseEvent(a,"click",!1,!1,c)}else d.selected=!0,this.simulateMouseEvent(d,"mousedown",!1,!1,c),this.simulateEvent(a,"focus"),(this._isChrome()||this._isSafari()||this._isOpera())&&this.simulateEvent(a,"focusin"),this.simulateMouseEvent(d,"mouseup",!1,!1,c),this.simulateMouseEvent(a,
"change"),this.simulateMouseEvent(d,"click",!1,!1,c)};
Sahi.prototype._setSelected=function(a,b,c){if(null!=b){this.checkNull(a,"_setSelected");this.checkVisible(a);if(this.isApplet(a))return a.setSelected(b);if(this.isFlexObj(a))return null!=this.lookInside&&(a=a.inside(this.lookInside)),a.choose(b);this.xyoffsets=new Sahi.Dict;var d=a.options.length;if("select-one"==a.type)if(1<a.size)this.selectOptionWithSize(a,b);else{c=window.navigator.pointerEnabled;d=this.isMsPointerEventsEnabled();c&&this.simulateMouseEvent(a,"pointerdown");d&&this.simulateMouseEvent(a,
"MSPointerDown");this.simulateMouseEvent(a,"mousedown");(this._isIE()||this._isChrome())&&this.simulateEvent(a,"focusin");this.simulateEvent(a,"focus");c&&this.simulateMouseEvent(a,"pointerup");d&&this.simulateMouseEvent(a,"MSPointerUp");this.simulateMouseEvent(a,"mouseup");this.simulateMouseEvent(a,"click");this.selectOption(a,b);return}else{this.isArray(b)||(b=[b]);if(!c)for(var e=0;e<d;e++)a.options[e].selected=!1;for(e=0;e<b.length;e++)this.selectOption(a,b[e],0<e||c)}this.setLastBlurFn(function(){try{_sahi._isIE()&&
_sahi.simulateEvent(a,"focusout"),_sahi.simulateEvent(a,"blur")}catch(b){}})}};Sahi.prototype._check=function(a){this.checkNull(a,"_check");a.checked||this._click(a)};Sahi.prototype._uncheck=function(a){this.checkNull(a,"_uncheck");a.checked&&this._click(a)};Sahi.prototype._wait=function(a,b){return b?eval(b):!1};Sahi.prototype.getTextNodesIn=function(a){var b=[];if(3==a.nodeType)b.push(a);else{a=a.childNodes;for(var c=0,d=a.length;c<d;++c)b.push.apply(b,this.getTextNodesIn(a[c]))}return b};
Sahi.prototype.getDocumentNode=function(a){"iframe"==a.tagName.toLowerCase()?a=a.contentWindow.document.body:this.isWindow(a)&&(a=a.document.body);return a};Sahi.prototype.getStartEndIndexes=function(a,b){var c=-1,d=-1,e=this.getArrayNameAndIndex(a,!0),f=e.index,e=e.name;-1==f&&(f=0);if(e instanceof RegExp){for(var h=null,k=0;k<=f&&(h=e.exec(b),null!=h);k++);h&&(c=h.index,d=e.lastIndex)}else{h=-1;for(k=0;k<=f&&(h=b.indexOf(e,h+1),-1!=h);k++);-1!=h&&(c=h,d=c+e.length)}return[c,d]};
Sahi.prototype._selectTextRange=function(a,b,c){this.checkNull(a,"_selectTextRange");var d=0,e=0;a=this.getDocumentNode(a);var f=-1!=this.findInArray(this.textboxTypes,a.type)||"textarea"==a.type?a.value:a.textContent;f&&(b=this.getStartEndIndexes(b,f),d=b[0],e=b[1]);this._selectRange(a,d,e,c)};
Sahi.prototype._selectRange=function(a,b,c,d){if(-1!=b&&-1!=c){"after"==d&&(b=c);this.checkNull(a,"_selectRange");a=this.getDocumentNode(a);var e=this.getWindow(a);if(-1!=this.findInArray(this.textboxTypes,a.type)||"textarea"==a.type)if("before"==d&&(c=b),a.createTextRange){var f=a.createTextRange();f.collapse(!0);f.moveStart("character",b);this._isIE()&&(c-=b);f.moveEnd("character",c);f.select();a.focus()}else"undefined"!=typeof a.selectionStart?(a.selectionStart=b,a.selectionEnd=c,a.focus()):a.setSelectionRange&&
(a.focus(),a.setSelectionRange(b,c));else if(document.createRange&&window.getSelection){f=e.document.createRange();f.selectNodeContents(a);a=this.getTextNodesIn(a);for(var h=!1,k=0,l,g=0,m;m=a[g++];){l=k+m.length;if(!h&&b>=k&&(b<l||b==l&&g<a.length)){if("before"==d){if(b-k==m.length&&c!=b&&g+1<a.length){b=a[g];f.setStartBefore(b);f.setEnd(b,0);f.collapse(!0);break}f.setStart(m,b-k);f.setEnd(m,b-k);break}f.setStart(m,b-k);h=!0}if(h&&c<=l){f.setEnd(m,c-k);break}k=l}b=e.getSelection();b.removeAllRanges();
b.addRange(f)}else document.selection&&document.body.createTextRange&&(f=this.getWindow(a).document.body.createTextRange(),f.moveToElementText(a),f.collapse(!0),f.moveEnd("character",c),f.moveStart("character",b),f.select())}};
Sahi.prototype._mapDomainToIP=function(a,b){a=0==a.indexOf("http")?a:"http://"+a;b&&this._addToSession(a);var c="domain\x3d"+encodeURIComponent(".*"+a.replace(/[.]/g,"[.]")+".*"),c=c+("\x26ip\x3d"+encodeURIComponent(null==b?"":b)),c=c+("\x26sahisid\x3d"+_sahi.sid);this.sendToServer("/_s_/dyn/pro/in.co.sahi.plugin.Rerouter_mapDomainToIP?"+c)};
var SahiScrollAndCapture=function(a,b,c,d,e,f,h,k,l,g,m,n,p){this.el=d?d:window;this.mode=p;this.win=c;this.img=b;this.delay=e?e:100;_sahi._isPhantomJS()&&5E3>this.delay&&(this.delay=5E3);this.stepId=a;this.scrollLimit=f?f:2E5;this.trim=!0===h;this.fileSysPath=k?k:null;this.noLog=!0===l;this.wrapped=[];this.isPhantomJS=n;this.format=g&&"-1"!=g?g:_sahi.getImageFormat();this.resizePercentage=m&&-1!=m?m:_sahi.getResizePercentage()};
SahiScrollAndCapture.prototype.init=function(){this.isPhantomJS?this.schedulePhantomJSStart():this.scheduleStart()};SahiScrollAndCapture.prototype.wrap=function(a){var b=this;null==this.wrapped[a]&&(this.wrapped[a]=function(){return a.apply(b,arguments)});return this.wrapped[a]};SahiScrollAndCapture.prototype.scheduleStart=function(){setTimeout(this.wrap(this.start),this.delay)};SahiScrollAndCapture.prototype.schedulePhantomJSStart=function(){setTimeout(this.wrap(this.phantomJSStart),this.delay)};
SahiScrollAndCapture.prototype.phantomJSStart=function(){this.phantomJSImg=_sahi.takeSnapShotPhantomJS(999,999,this.format);this.scheduleStart()};
SahiScrollAndCapture.prototype.start=function(){var a=this.phantomJSImg,a=this.isPhantomJS?_sahi.fetchTopXY(a):_sahi.fetchTopXY();this.img&&(this.img.style.display="none");this.overflowEl=1==this.mode?this.win.document.documentElement:this.el;this.originalOverflowX=_sahi._style(this.overflowEl,"overflow-x");this.originalOverflowY=_sahi._style(this.overflowEl,"overflow-y");this.overflowEl.style.overflowX="hidden";this.overflowEl.style.overflowY="hidden";this.originalBorder=this.overflowEl.style.border;
this.overflowEl.style.border="none";this.left=a[0];this.top=a[1];a=1==this.mode?_sahi.getWinDimensions(this.win):_sahi.getDimensions(this.el);this.width=a[0];this.height=a[1];this.innerHeight=a[1];this.scrollHeight=1==this.mode?parseInt(this.win.document.body.scrollHeight):parseInt(this.el.scrollHeight);this.scrollHeight>this.scrollLimit&&(this.scrollHeight=this.scrollLimit);1==this.mode?this.win.scrollTo(0,0):this.el.scrollTop=0;this.counter=0;this.scheduleProceed()};
SahiScrollAndCapture.prototype.scheduleProceed=function(){setTimeout(this.wrap(this.proceed),this.delay)};
SahiScrollAndCapture.prototype.proceed=function(){this.isPhantomJS?_sahi.takeSnapShotPhantomJS(this.stepId,this.counter,this.format):_sahi.takeSnapShot(this.stepId,this.counter,this.top,this.left,this.height,this.width,this.format,!1);this.counter++;"frameset"==(""+this.win.document.body.tagName).toLowerCase()||this.isPhantomJS?this.logAndStitch():this.scrollHeight-this.innerHeight>this.innerHeight&&!this.isPhantomJS?(1==this.mode?this.win.scrollBy(0,this.innerHeight):this.el.scrollTop+=this.innerHeight,
this.scrollHeight-=this.innerHeight,this.scheduleProceed()):0>=this.scrollHeight-this.innerHeight?this.logAndStitch():(1==this.mode?this.win.scrollBy(0,this.scrollHeight-this.innerHeight):this.el.scrollTop+=this.scrollHeight-this.innerHeight,this.scrollHeight-=this.innerHeight,this.top=this.top+this.innerHeight-this.scrollHeight,this.height=this.scrollHeight,this.scheduleLast())};SahiScrollAndCapture.prototype.scheduleStitch=function(){setTimeout(this.wrap(this.stitch),this.delay)};
SahiScrollAndCapture.prototype.stitch=function(){if(1!=this.mode||this.el==window||_sahi.isWindow(this.el))lastImageFilePath=_sahi.stitchSnapShots(this.stepId,this.counter,"V",-1,-1,-1,-1,this.noLog,this.format,this.resizePercentage,this.fileSysPath);else{var a=_sahi._position(this.el),b=a[1],a=a[0];this.isPhantomJS&&(b+=this.top,a+=this.left);lastImageFilePath=_sahi.stitchSnapShots(this.stepId,this.counter,"V",b,a,this.el.offsetHeight,this.el.offsetWidth,this.noLog,this.format,this.resizePercentage,
this.fileSysPath)}_sahi.lastImageFilePath=null;this.isAssert?this.assertImage(lastImageFilePath):(this.noLog||(_sahi.lastImageFilePath=lastImageFilePath),_sahi.afterEval())};SahiScrollAndCapture.prototype.scheduleLast=function(){setTimeout(this.wrap(this.last),this.delay)};
SahiScrollAndCapture.prototype.last=function(){this.isPhantomJS?_sahi.takeSnapShotPhantomJS(this.stepId,this.counter,this.format):_sahi.takeSnapShot(this.stepId,this.counter,this.top,this.left,this.height,this.width,this.format,!1);this.counter++;this.logAndStitch()};SahiScrollAndCapture.prototype.logAndStitch=function(){this.overflowEl.style.overflowX=this.originalOverflowX;this.overflowEl.style.overflowY=this.originalOverflowY;this.overflowEl.style.border=this.originalBorder;this.scheduleStitch()};
SahiScrollAndCapture.prototype.setAssertProperties=function(a,b,c){this.isAssert=!0;this.refImagePath=a;this.threshold=b;this.displayOnSuccess=c};
SahiScrollAndCapture.prototype.assertImage=function(a){var b=_sahi._callServer("Driver_getCompareImagesData","actualImage\x3d"+a+"\x26refImage\x3d"+this.refImagePath+"\x26stepId\x3d"+this.stepId+"\x26isSnapShot\x3dtrue").split(",");a=parseFloat(b.shift());_sahi.lastImageFilePath=b.toString();b="Score: "+a;if(isNaN(a)||a>this.threshold)_sahi.currentType="FAILURE",_sahi.markStepDone(_sahi.currentStepId,_sahi.currentType,b,_sahi.lastImageFilePath),_sahi.lastImageFilePath=null,_sahi.waitForLoad=_sahi.SAHI_MAX_WAIT_FOR_LOAD;
else return _sahi.currentType="SUCCESS",this.displayOnSuccess||(_sahi.lastImageFilePath=null),_sahi._log(b,_sahi.currentType),_sahi.afterEval(),a};
Sahi.prototype._assertEqualImages=function(a,b,c,d,e){if(!this.SKIP_ASSERT_SNAPSHOTS)if(this.fork(3E4),null==c&&(c=this.DEFAULT_IMAGE_COMPARISON_THRESHOLD),b=_sahi._callServer("Driver_getCompareImagesData","actualImage\x3d"+b+"\x26refImage\x3d"+a+"\x26stepId\x3d"+this.currentStepId+"\x26isSnapShot\x3dfalse").split(","),a=parseFloat(b.shift()),_sahi.lastImageFilePath=b.toString(),b="Score: "+a,isNaN(a)||a>c)_sahi.currentType="FAILURE",_sahi.markStepDone(_sahi.currentStepId,_sahi.currentType,e+"\n"+
b,_sahi.lastImageFilePath),_sahi.lastImageFilePath=null,_sahi.waitForLoad=_sahi.SAHI_MAX_WAIT_FOR_LOAD;else return _sahi.currentType="SUCCESS",d||(_sahi.lastImageFilePath=null),_sahi._log(b,_sahi.currentType),_sahi.afterEval(),a};Sahi.prototype.getFirstFrameInFrameset=function(a){if("frameset"==(""+a.document.body.tagName).toLowerCase()){var b=a.frames;if(b)for(var c=0;c<b.length;c++){var d=b[c];try{if(0<d.document.body.offsetHeight)return d}catch(e){}}}return a};
Sahi.prototype.placePattern=function(a,b){null==b&&(b=[0,0]);a.focus();var c=a.document.elementFromPoint(b[0],b[1]);c&&"APPLET"==c.tagName&&(c.style.top="1px",this.appletOnTop=c);a.scrollTo(b[0],b[1]);var d=this.getFirstFrameInFrameset(a),e=d.document.getElementById("sahi_pattern");e?e.style.display="block":(e=new Image,e.id="sahi_pattern",e.src="/_s_/spr/images/pattern.png",d.document.body.appendChild(e),e.style.position="absolute",e.style.top=b[1]+"px",e.style.left=b[0]+"px",e.style.zIndex=""+this.getPatternZIndex(c));
return e};Sahi.prototype.getPatternZIndex=function(a){if(!a)return 2147483647;var b=2147483647;try{var c=this._style(a,"z-index"),c=parseInt(c);2147483647<c&&(2147483647<=c?a.style.zIndex="2147483646":b=c+1)}catch(d){}return b};Sahi.prototype.removePatternAndScroll=function(a){this.removePattern(this.getWindow(a));this.scrollIntoView(a)};Sahi.prototype.scrollIntoView=function(a){return(this.isFlexObj(a)?a.object:a).scrollIntoView()};
Sahi.prototype.removePattern=function(a){var b=this.appletOnTop;b&&(b.style.top="0px",this.appletOnTop=null);if(a=a.document.getElementById("sahi_pattern"))a.style.display="none"};
Sahi.prototype._takePageScreenShot=function(a,b,c,d){if(!this.SKIP_SCREENSHOTS){null===a&&(a=this._eval(top));var e=null,f=null,h=!0,k=null,l=null,g=1;d&&(d.delay&&(e=d.delay),d.scrollLimit&&(f=d.scrollLimit),d.trim&&(h=d.trim),d.format&&(k=d.format),d.resizePercentage&&(l=d.resizePercentage),d.mode&&(g=d.mode));0<arguments.length&&this.checkNull(a,"_takePageScreenShot");this.fork(6E4);var m=window;a&&a!=window&&(m=this.getWindow(a));var n=this.placePattern(m,1==g?[0,0]:this._position(a));this.takeScrolledScreenShot(m,
n,a,e,f,h,b,c,k,l,g)}};Sahi.prototype.takeScrolledScreenShot=function(a,b,c,d,e,f,h,k,l,g,m){(new SahiScrollAndCapture(this.currentStepId,b,a,c,d,e,f,h,k,l,g,_sahi._isPhantomJS(),m)).init()};Sahi.prototype.fetchTopXY=function(a){return a&&null!==a&&void 0!==a?eval("("+this.sendToServer("/_s_/dyn/Player_getTopXY?imagePath\x3d"+a)+")"):eval("("+this.sendToServer("/_s_/dyn/Player_getTopXY")+")")};Sahi.DRAG_DROP_SPEED=1;Sahi.DRAG_DROP_SEGMENTS=200;Sahi.DRAG_DROP_WAVER=1;
Sahi.DRAG_DROP_MAX_HOVER_AT_END=5;var SahiDTProxy=function(){this.data={}};SahiDTProxy.prototype.setData=function(a,b){this.data[a]=b;return!0};SahiDTProxy.prototype.getData=function(a){return this.data[a]};SahiDTProxy.prototype.clearData=function(a){a?delete this.data[a]:this.data={}};
Sahi.DragDropper=function(a,b,c,d,e){this.draggable=a;this.droppable=b;this.offsetX=c;this.offsetY=d;this.isRelative=e;this.start=function(){this.dataTransfer=new SahiDTProxy;var a=window.navigator.pointerEnabled,b=_sahi.isMsPointerEventsEnabled();a&&_sahi.simulateMouseEvent(this.draggable,"pointerover");b&&_sahi.simulateMouseEvent(this.draggable,"MSPointerOver");_sahi.simulateMouseEvent(this.draggable,"mouseover");a&&_sahi.simulateMouseEvent(this.draggable,"pointermove");b&&_sahi.simulateMouseEvent(this.draggable,
"MSPointerMove");_sahi.simulateMouseEvent(this.draggable,"mousemove");a&&_sahi.simulateMouseEvent(this.draggable,"pointerdown");b&&_sahi.simulateMouseEvent(this.draggable,"MSPointerDown");_sahi.simulateMouseEvent(this.draggable,"mousedown");a&&_sahi.simulateMouseEvent(this.draggable,"pointermove");b&&_sahi.simulateMouseEvent(this.draggable,"MSPointerMove");_sahi.simulateMouseEvent(this.draggable,"mousemove");_sahi.simulateDragEvent(this.draggable,"dragstart",this.dataTransfer);_sahi.simulateDragEvent(this.draggable,
"drag",this.dataTransfer);this.initPos=a=_sahi.findClientPosWithOffset(this.draggable);this.initX=a[0];this.initY=a[1];this.stage=this.destY=this.destX=0;this.segments=Sahi.DRAG_DROP_SEGMENTS;this.endHoverCount=0;this.lastMovedEl=null};this.execute=function(){this.start();this.proceed()};this.proceed=function(){if(this.stage<this.segments){this.stage++;this.move(this.stage);var a=this;window.setTimeout(function(){a.proceed()},Sahi.DRAG_DROP_SPEED)}else this.endHoverCount++<Sahi.DRAG_DROP_MAX_HOVER_AT_END?
(this.move(this.stage),a=this,window.setTimeout(function(){a.proceed()},Sahi.DRAG_DROP_SPEED)):(this.finish(),_sahi.afterEval())};this.move=function(a){var b=[0,0];"DRAG_RELATIVE"==this.isRelative?b=this.initPos:"DROP_RELATIVE"==this.isRelative&&(b=_sahi.findClientPosWithOffset(this.droppable));this.destX=b[0]+(this.offsetX?this.offsetX:0);this.destY=b[1]+(this.offsetY?this.offsetY:0);b=Math.floor(this.initX+a*(this.destX-this.initX)/this.segments);a=Math.floor(this.initY+a*(this.destY-this.initY)/
this.segments+(0==a%2?Sahi.DRAG_DROP_WAVER:0));var c=document.elementFromPoint(b,a);if(null!=c)try{var d=window.navigator.pointerEnabled,e=_sahi.isMsPointerEventsEnabled();this.lastMovedEl!=c&&(this.lastMovedEl&&(d&&_sahi.simulateMouseEventXY(this.lastMovedEl,"pointerout",b,a),e&&_sahi.simulateMouseEventXY(this.lastMovedEl,"MSPointerOut",b,a),_sahi.simulateMouseEventXY(this.lastMovedEl,"mouseout",b,a),_sahi.simulateDragEventXY(this.lastMovedEl,"dragleave",b,a,this.dataTransfer)),d&&_sahi.simulateMouseEventXY(c,
"pointerenter",b,a),_sahi.simulateMouseEventXY(c,"mouseenter",b,a),d&&_sahi.simulateMouseEventXY(c,"pointermove",b,a),e&&_sahi.simulateMouseEventXY(c,"MSPointerMove",b,a),_sahi.simulateMouseEventXY(c,"mousemove",b,a),d&&_sahi.simulateMouseEventXY(c,"pointerover",b,a),e&&_sahi.simulateMouseEventXY(c,"MSPointerOver",b,a),_sahi.simulateMouseEventXY(c,"mouseover",b,a),d&&_sahi.simulateMouseEventXY(c,"pointermove",b,a),e&&_sahi.simulateMouseEventXY(c,"MSPointerMove",b,a),_sahi.simulateMouseEventXY(c,"mousemove",
b,a),_sahi.simulateDragEventXY(c,"dragenter",b,a,this.dataTransfer),this.lastMovedEl=c);try{d&&_sahi.simulateMouseEventXY(this.draggable,"pointermove",b,a),e&&_sahi.simulateMouseEventXY(this.draggable,"MSPointerMove",b,a),_sahi.simulateMouseEventXY(this.draggable,"mousemove",b,a),d&&_sahi.simulateMouseEventXY(c,"pointermove",b,a),e&&_sahi.simulateMouseEventXY(c,"MSPointerMove",b,a),_sahi.simulateMouseEventXY(c,"mousemove",b,a)}catch(m){}_sahi.simulateDragEventXY(this.draggable,"drag",b,a,this.dataTransfer);
_sahi.simulateDragEventXY(c,"dragover",b,a,this.dataTransfer)}catch(n){}};this.finish=function(){var a=this.destX,b=this.destY,c=window.navigator.pointerEnabled,d=_sahi.isMsPointerEventsEnabled();this.droppable&&(c&&_sahi.simulateMouseEventXY(this.droppable,"pointermove",a,b),d&&_sahi.simulateMouseEventXY(this.droppable,"MSPointerMove",a,b),_sahi.simulateMouseEventXY(this.droppable,"mousemove",a,b));c&&_sahi.simulateMouseEventXY(this.draggable,"pointermove",a,b);d&&_sahi.simulateMouseEventXY(this.draggable,
"MSPointerMove",a,b);_sahi.simulateMouseEventXY(this.draggable,"mousemove",a,b);_sahi.simulateDragEventXY(this.draggable,"drag",a,b,this.dataTransfer);this.droppable&&this.lastMovedEl!=this.droppable&&(c&&_sahi.simulateMouseEventXY(this.lastMovedEl,"pointerout",a,b),d&&_sahi.simulateMouseEventXY(this.lastMovedEl,"MSPointerOut",a,b),_sahi.simulateMouseEventXY(this.lastMovedEl,"mouseout",a,b),_sahi.simulateDragEventXY(this.lastMovedEl,"dragleave",a,b,this.dataTransfer),_sahi.simulateDragEventXY(this.droppable,
"dragenter",a,b,this.dataTransfer),c&&_sahi.simulateMouseEventXY(this.droppable,"pointerover",a,b),d&&_sahi.simulateMouseEventXY(this.droppable,"MSPointerOver",a,b),_sahi.simulateMouseEventXY(this.droppable,"mouseover",a,b));_sahi.simulateDragEventXY(this.draggable,"drag",a,b,this.dataTransfer);this.droppable&&(_sahi.simulateDragEventXY(this.droppable,"dragover",a,b,this.dataTransfer),c&&_sahi.simulateMouseEventXY(this.droppable,"pointerup",a,b),d&&_sahi.simulateMouseEventXY(this.droppable,"MSPointerUp",
a,b),_sahi.simulateMouseEventXY(this.droppable,"mouseup",a,b));c&&_sahi.simulateMouseEventXY(this.draggable,"pointerup",a,b);d&&_sahi.simulateMouseEventXY(this.draggable,"MSPointerUp",a,b);_sahi.simulateMouseEventXY(this.draggable,"mouseup",a,b);this.droppable&&_sahi.simulateDragEventXY(this.droppable,"drop",a,b,this.dataTransfer);try{_sahi.simulateDragEventXY(this.draggable,"dragend",a,b,this.dataTransfer),_sahi.simulateMouseEventXY(this.draggable,"click",a,b),c&&_sahi.simulateMouseEventXY(this.draggable,
"pointermove",a,b),d&&_sahi.simulateMouseEventXY(this.draggable,"MSPointerMove",a,b),_sahi.simulateMouseEventXY(this.draggable,"mousemove",a,b),c&&_sahi.simulateMouseEventXY(this.draggable,"pointerout",a,b),d&&_sahi.simulateMouseEventXY(this.draggable,"MSPointerOut",a,b),_sahi.simulateMouseEventXY(this.draggable,"mouseout",a,b)}catch(e){}}};Sahi.prototype.dragDropXYCommon=function(a,b,c,d,e){(new Sahi.DragDropper(a,b,c,d,e)).execute()};
Sahi.prototype._dragDrop=function(a,b,c,d){if(this.isFlexObj(a))return b.setAsDroppable(),a.dragDrop();this.fork(3E4);this.checkNull(a,"_dragDrop",1,"draggable");this.checkNull(b,"_dragDrop",2,"droppable");this.dragDropXYCommon(a,b,c,d,"DROP_RELATIVE")};Sahi.prototype._dragDropXY=function(a,b,c,d){this.fork(3E4);if(this.isFlexObj(a))return a.dragDropXY(b,c);this.checkNull(a,"_dragDropXY",1,"draggable");return this.dragDropXYCommon(a,null,b,c,d?"DRAG_RELATIVE":!1)};