Sahi.prototype.setRecorderModeJava=function(){this.controllerURL="/_s_/spr/controllerAlt.htm";this.controllerHeight=400;this.controllerWidth=420;this.recorderClass="StepWiseRecorder";Sahi.prototype.getExpectPromptAssert=function(a){return"assertEquals("+this.quotedEscapeValue(a)+", b.lastPrompt());"};Sahi.prototype.getExpectConfirmAssert=function(a){return"assertEquals("+this.quotedEscapeValue(a)+", b.lastConfirm());"};Sahi.prototype.getAlertAssert=function(a){return"assertEquals("+this.quotedEscapeValue(a)+
", b.lastAlert());"};Sahi.prototype.getExpectPromptScript=function(a,e){return"b."+this.getPopupDomainPrefixes()+"expectPrompt("+this.quotedEscapeValue(a)+", "+this.quotedEscapeValue(e)+")"};Sahi.prototype.getExpectConfirmScript=function(a,e){return"b."+this.getPopupDomainPrefixes()+"expectConfirm("+this.quotedEscapeValue(a)+", "+e+")"};Sahi.prototype.getNavigateToScript=function(a){return"b."+this.getPopupDomainPrefixes()+"navigateTo("+this.quotedEscapeValue(a)+");"};Sahi.prototype.getNavigateToWithSizeScript=
function(a,e,c){return"b."+this.getPopupDomainPrefixes()+"openWindow("+this.quotedEscapeValue(a)+","+this.quotedEscapeValue(e)+","+c+");"};Sahi.prototype.getScript=function(a,e,c,g){var d=a[0];a=this.escapeDollar(this.getAccessor1(d));if(null==a)return null;0==a.indexOf("_")&&(a=a.substring(1));e=d.event;var f=d.value,d=d.type;this.getPopupName();var b=null;null==f&&(f="");if("keydown"==c){if(g&&112<=g.keyCode&&123>=g.keyCode&&!g.charCode&&(b=a+'.keyPress("['+g.keyCode+',0]");'),!b)return null}else"_click"==
e?b=c&&"contextmenu"==c.toLowerCase()?a+".rightClick();":"_checkbox"==d&&!1==f||"_radio"==d?a+".check();":"_checkbox"==d&&!0==f?a+".uncheck();":a+".click();":"_setValue"==e?b=a+".setValue("+this.quotedEscapeValue(f)+");":"_setSelected"==e?b=a+".choose("+this.quotedEscapeValue(f)+");":"_setFile"==e&&(b=a+".setFile("+this.quotedEscapeValue(f)+");");return b=this.addPopupDomainPrefixes(b)};Sahi.prototype.escapeDollar=function(a){return a};Sahi.prototype.getAccessor1=function(a){if(null==a||""==""+a.shortHand||
null==a.shortHand)return null;var e="b."+a.type.substring(1)+"("+this.escapeForScript(a.shortHand)+")";if(a.relationStr){var c;0==a.relationStr.indexOf("_near")?c="near":0==a.relationStr.indexOf("_in")&&(c="in");0==a.type.indexOf("_")&&(a.type=a.type.substring(1));0==this.anchorStr.indexOf("_")&&(this.anchorStr=this.anchorStr.substring(1));e="b."+a.type+"("+this.escapeForScript(a.shortHand)+")."+c+"(b."+this.anchorStr+")"}return e};this.language={ASSERT_EXISTS:"assertTrue(\x3caccessor\x3e.exists());",
ASSERT_VISIBLE:"assertTrue(\x3caccessor\x3e.isVisible());",ASSERT_EQUAL_TEXT:"assertEquals(\x3cvalue\x3e, \x3caccessor\x3e.text());",ASSERT_CONTAINS_TEXT:"assertTrue(\x3caccessor\x3e.text().contains(\x3cvalue\x3e));",ASSERT_EQUAL_VALUE:"assertEquals(\x3cvalue\x3e, \x3caccessor\x3e.value());",ASSERT_SELECTION:"assertEquals(\x3cvalue\x3e, \x3caccessor\x3e.selectedText());",ASSERT_CHECKED:"assertTrue(\x3caccessor\x3e.checked());",ASSERT_NOT_CHECKED:"assertFalse(\x3caccessor\x3e.checked());",POPUP:"b.popup(\x3cwindow_name\x3e).",
DOMAIN:"b.domain(\x3cdomain\x3e)."};SflWrapper.convertToFn=function(a){a="string"==typeof a?eval("("+a+")"):a;return'b.flex("'+a.objectId+'").find("'+a.api+'", '+this.toJSON(a.args[0])+")"};SflWrapper.prototype.getStep=function(a,e,c){return"b."+e+"."+a+"("+(c?c:"")+");"}};
Sahi.prototype.setRecorderModeRuby=function(){this.controllerURL="/_s_/spr/controllerAlt.htm";this.controllerHeight=400;this.controllerWidth=420;this.recorderClass="StepWiseRecorder";Sahi.prototype.getExpectPromptAssert=function(a){return"assert_equal("+this.quotedEscapeValue(a)+", @b.last_prompt())"};Sahi.prototype.getAlertAssert=function(a){return"assert_equal("+this.quotedEscapeValue(a)+", @b.last_alert())"};Sahi.prototype.getExpectConfirmAssert=function(a){return"assert_equal("+this.quotedEscapeValue(a)+
", @b.last_confirm())"};Sahi.prototype.getExpectPromptScript=function(a,e){return"@b."+this.getPopupDomainPrefixes()+"expect_prompt("+this.quotedEscapeValue(a)+", "+this.quotedEscapeValue(e)+")"};Sahi.prototype.getExpectConfirmScript=function(a,e){return"@b."+this.getPopupDomainPrefixes()+"expect_confirm("+this.quotedEscapeValue(a)+", "+e+")"};Sahi.prototype.getNavigateToScript=function(a){return"@b."+this.getPopupDomainPrefixes()+"navigate_to("+this.quotedEscapeValue(a)+")"};Sahi.prototype.getScript=
function(a,e,c,g){var d=a[0];a=this.escapeDollar(this.getAccessor1(d));if(null==a)return null;0==a.indexOf("_")&&(a=a.substring(1));e=d.event;var f=d.value,d=d.type;this.getPopupName();var b=null;null==f&&(f="");if("keydown"==c){if(g&&112<=g.keyCode&&123>=g.keyCode&&!g.charCode&&(b=a+'.key_press("['+g.keyCode+',0]");'),!b)return null}else"_click"==e?b=c&&"contextmenu"==c.toLowerCase()?a+".right_click":"_checkbox"==d&&!1==f||"_radio"==d?a+".check()":"_checkbox"==d&&!0==f?a+".uncheck()":a+".click":
"_setValue"==e?b=a+".value \x3d "+this.quotedEscapeValue(f):"_setSelected"==e?b=a+".choose("+this.quotedEscapeValue(f)+")":"_setFile"==e&&(b=a+".file \x3d "+this.quotedEscapeValue(f));return b=this.addPopupDomainPrefixes(b)};Sahi.prototype.escapeDollar=function(a){return a};Sahi.prototype.getAccessor1=function(a){if(null==a||""==""+a.shortHand||null==a.shortHand)return null;var e="@b."+a.type.substring(1)+"("+this.escapeForScript(a.shortHand)+")";if(a.relationStr){var c;0==a.relationStr.indexOf("_near")?
c="near":0==a.relationStr.indexOf("_in")&&(c="in");0==a.type.indexOf("_")&&(a.type=a.type.substring(1));0==this.anchorStr.indexOf("_")&&(this.anchorStr=this.anchorStr.substring(1));e="@b."+a.type+"("+this.escapeForScript(a.shortHand)+")."+c+"(@b."+this.anchorStr+")"}return e};this.language={ASSERT_EXISTS:"assert(\x3caccessor\x3e.exists?)",ASSERT_VISIBLE:"assert(\x3caccessor\x3e.visible?);",ASSERT_EQUAL_TEXT:"assert_equal(\x3cvalue\x3e, \x3caccessor\x3e.text);",ASSERT_CONTAINS_TEXT:"assert(\x3caccessor\x3e.text.contains(\x3cvalue\x3e));",
ASSERT_EQUAL_VALUE:"assert_equal(\x3cvalue\x3e, \x3caccessor\x3e.value);",ASSERT_SELECTION:"assert_equal(\x3cvalue\x3e, \x3caccessor\x3e.selected_text);",ASSERT_CHECKED:"assert(\x3caccessor\x3e.checked?);",ASSERT_NOT_CHECKED:"assert(!\x3caccessor\x3e.checked?);",POPUP:"@b.popup(\x3cwindow_name\x3e).",DOMAIN:"@b.domain(\x3cdomain\x3e)."}};
Sahi.prototype.setRecorderModeTestmaker=function(){eval(this.sendToServer("/_s_/spr/ext/selenium/locatorBuilders.js"));var a=function(){};a.info=a.warn=a.prototype.exception=a.prototype.error=a.prototype.debug=function(a){};DummyBot=function(){this.locationStrategies=[]};DummyBot.prototype.findElement=function(a){return this._bySeleniumLocator(a)};LocatorBuilders.prototype.pageBot=function(){return new DummyBot};this.recorderClass="StepWiseRecorder";Sahi.prototype.getExpectPromptScript=function(a,
c){return this.toJSON([this.getStepObj("expectPrompt",this.quotedEscapeValue(a),this.quotedEscapeValue(c))])};Sahi.prototype.getExpectConfirmScript=function(a,c){return this.toJSON([this.getStepObj("expectConfirm",this.quotedEscapeValue(a),c)])};Sahi.prototype.getNavigateToScript=function(a){return this.toJSON([this.getStepObj("navigateTo","",this.quotedEscapeValue(a)),this.getStepObj("navigateTo","",this.quotedEscapeValue(a),"selenium")])};Sahi.prototype.getStepObj=function(a,c,g,d,f){var b={};b.popup=
f?f:"";b.dialect=d?d:"sahi";b.action=a;b.accessor=c;b.value=g;return b};Sahi.prototype.getScript=function(a,c,g,d){var f=this.getPopupName(),b=[];if("keydown"==g){if(d&&112<=d.keyCode&&123>=d.keyCode&&!d.charCode){for(var h=0;h<a.length;h++){var m=a[h],n=this.escapeDollar(this.getAccessor1(m)),k="keyPress",l=this.toJSON("["+d.keyCode+",0]");b[b.length]=this.getStepObj(k,n,l,"sahi",f)}return this.toJSON(b)}return null}for(h=0;h<a.length;h++)try{var m=a[h],k=m.event.replace(/^_/,""),n=this.escapeDollar(this.getAccessor1(m)),
l=null;if("setValue"==k||"setSelected"==k||"setFile"==k)l=m.value,null==l&&(l=""),l=this.toJSON(l);"click"==k&&g&&"contextmenu"==g.toLowerCase()&&(k="rightClick");b[b.length]=this.getStepObj(k,n,l,"sahi",f)}catch(q){}a=this.getSeleniumAccessors(c);for(h=0;h<a.length;h++)try{b[b.length]=this.getStepObj(k,this.quotedEscapeValue(a[h][0]),l,"selenium",f)}catch(p){this._alert(p)}return this.toJSON(b)};Sahi.prototype.getSeleniumAccessors=function(a){return(new LocatorBuilders(window)).buildAll(a)};Sahi.prototype.escapeDollar=
function(a){return a};Sahi.prototype.getAccessor1=function(a){if(null==a||""==""+a.shortHand||null==a.shortHand)return null;this.lastIdentifiedElementType=a.type;a=a.type+"("+this.escapeForScript(a.shortHand)+")";0==a.indexOf("_")&&(a=a.substring(1));return a};Sahi.prototype.sendIdentifierInfo=function(a,c,g,d){d=eval(this.addSahi("_"+c));c=this.identify(d).assertions;d=this.getSeleniumAccessors(d);for(var f=[],b=0;b<d.length;b++)f[f.length]=this.quotedEscapeValue(d[b][0]);a=this.toJSON({type:this.lastIdentifiedElementType,
accessors:{sahi:a,selenium:f},assertions:c,value:g});this.sendToServer("/_s_/dyn/Driver_setLastIdentifiedElement?element\x3d"+encodeURIComponent(a))};SflWrapper.prototype.getStep=function(a,c,g){return this.toJSON([this.getStepObj(a,c,g)])};this.language={ASSERT_EXISTS:"assertExists__xxSAHIDIVIDERxx__\x3caccessor\x3e__xxSAHIDIVIDERxx__",ASSERT_VISIBLE:"assertVisible__xxSAHIDIVIDERxx__\x3caccessor\x3e__xxSAHIDIVIDERxx__",ASSERT_CONTAINS_TEXT:"assertContainsText__xxSAHIDIVIDERxx__\x3cvalue\x3e__xxSAHIDIVIDERxx__\x3caccessor\x3e",
ASSERT_EQUAL_VALUE:"assertEqual__xxSAHIDIVIDERxx__\x3caccessor\x3e.value__xxSAHIDIVIDERxx__\x3cvalue\x3e",ASSERT_NOT_CHECKED:"assertChecked__xxSAHIDIVIDERxx__\x3caccessor\x3e__xxSAHIDIVIDERxx__",POPUP:"popup(\x3cwindow_name\x3e).",DOMAIN:"domain(\x3cdomain\x3e)."}};