function SflWrapper(a){this.isSFL=!0;this.object=a;this.id=a._sahi_getFlexId();this.accessorAPINames=[];this.addAccessorFns()}
SflWrapper.prototype.loadRecordParameters=function(a){this.object._sahi_setRecordParameters("addRecordListenerToRoot",!0);this.object._sahi_setRecordParameters("addRecordListenerToRootOnMouseOver",!0);this.object._sahi_setRecordParameters("addRecordListenerToRootOnMouseOut",!0);this.object._sahi_setRecordParameters("addRecordListenerToRootOnClick",!0);this.object._sahi_setRecordParameters("addRecordListenerToRootOnClickForControllerOpen",!0);this.object._sahi_setRecordParameters("addRecordListener",
!0);this.object._sahi_setRecordParameters("addAllEventListener",!0);this.object._sahi_setRecordParameters("addEventListenerOnClick",!0);this.object._sahi_setRecordParameters("addEventListenerOnSetSelected",!0);this.object._sahi_setRecordParameters("addEventListenerOnSetValue",!0);this.object._sahi_setRecordParameters("reAttachRecorderListenersOnInterval",!0);this.object._sahi_setRecordParameters("debug",!1)};__fl_debugStr="";SflWrapper.prototype.debug=function(a){_sahi._debug(a)};
SflWrapper.prototype.display=function(a){if("object"==typeof _sahi){a=eval("("+a+")");for(var b=[],c=0;c<a.length;c++)b.push(SflWrapper.convertToFn(a[c]));_sahi.sendIdentifierInfo(b,b[0],a[0].value,_sahi.getPopupDomainPrefixes(),[])}};SflWrapper.prototype.record=function(a,b,c){"click"==b&&(c=null);"object"==typeof _sahi&&(a=SflWrapper.convertToFn(a),_sahi.isRecording()&&_sahi.recordStep(this.getStep(b,a,c)))};SflWrapper.prototype.getStep=function(a,b,c){return"_"+a+"("+b+(c?", "+c:"")+");"};
SflWrapper.prototype.exists=function(){try{return"Error:null_object"!=this.fetch("constructor")}catch(a){return!1}};SflWrapper.prototype.isVisible=function(){if(!this.exists())return!1;try{return!0==this.get("visible")}catch(a){return!1}};SflWrapper.prototype.xgetFlexApp=function(a){return-1!=navigator.appName.indexOf("Microsoft")?window[a]:document[a]};
SflWrapper.prototype.addAccessorFns=function(){for(var a="getGlobalXY click mouseDown mouseOver mouseUp dragDrop dragDropXY setAsDroppable setValue fetch choose listProperties introspect executeFn set highlight getValue getText getRowNo getColumnNo getGridData getTextOrToolTip getDataProviderData rightClick doubleClick identifyParent identifySelf".split(" "),b=0;b<a.length;b++){var c=a[b];this[c]=this.getFlexFn(c,!0)}};
SflWrapper.prototype.getFlexFn=function(a,b){return function(){var c=[];this.command&&(c[0]=this.command);for(var d=0;d<arguments.length;d++)c[c.length]=arguments[d];c={api:a,args:c};if(b){if((c=this.object._sahi_eval(c))&&"string"==typeof c&&0==c.indexOf("SAHI_FLEX_ERROR"))throw Error(c);return eval("("+c.replace(/[\r\n]/g,"\\r\\n")+")")}this.command=c;return this}};
SflWrapper.convertToFn=function(a){a="string"==typeof a?eval("("+a+")"):a;return'_f("'+a.objectId+'").'+a.api+"("+_sahi.toJSON(a.args[0])+")"};SflWrapper.prototype.addMetaData=function(a){a.apiName||(a.apiName=this.getAccessorAPIName(a.qn));SflWrapper.prototype[a.apiName]=this.getFlexFn(a.apiName);this.object._sahi_addMetaData(a)};SflWrapper.prototype.addEncaps=function(a,b){this.object._sahi_addEncaps(a,b)};SflWrapper.prototype.setStrictVisibility=function(a){this.object._sahi_setStrictVisibility(a)};
SflWrapper.prototype.find=function(a,b){return this[a](b)};SflWrapper.prototype.getAccessorAPIName=function(a){var b=a.indexOf("::");return-1!=b?(b=a.substring(b+2).toLowerCase(),0==a.indexOf("spark")?"s_"+b:b):a};SflWrapper.prototype.addAllRecorderListeners=function(){this.object._sahi_addAllRecorderListeners()};
SflWrapper.prototype.leftOf=function(a,b,c){c||(c=b);var d=this.command.args[0];"object"==typeof d&&null!=d.id?(d.leftOf=a.command,d.leftOf.offsetX=b,d.leftOf.offsetY=c):(this.command.args[0]={id:this.command.args[0],leftOf:a.command},this.command.args[0].leftOf.offsetX=b,this.command.args[0].leftOf.offsetY=c);return this};
SflWrapper.prototype.under=function(a,b,c){c||(c=b);var d=this.command.args[0];"object"==typeof d&&null!=d.id?(d.under=a.command,d.under.offsetX=b,d.under.offsetY=c):(this.command.args[0]={id:d,under:a.command},this.command.args[0].under.offsetX=b,this.command.args[0].under.offsetY=c);return this};
SflWrapper.prototype.rightOf=function(a,b,c){c||(c=b);var d=this.command.args[0];"object"==typeof d&&null!=d.id?(d.rightOf=a.command,d.rightOf.offsetX=b,d.rightOf.offsetY=c):(this.command.args[0]={id:d,rightOf:a.command},this.command.args[0].rightOf.offsetX=b,this.command.args[0].rightOf.offsetY=c);return this};SflWrapper.prototype.near=function(a){var b=this.command.args[0];"object"==typeof b&&null!=b.id?b.near=a.command:this.command.args[0]={id:this.command.args[0],near:a.command};return this};
SflWrapper.prototype.inside=function(a){var b=this.command.args[0];"object"==typeof b&&null!=b.id?b.inside=a.command:this.command.args[0]={id:this.command.args[0],inside:a.command};return this};SflWrapper.prototype.getData=function(){return this.getDataProviderData()};SflWrapper.prototype.get=function(a){return this.fetch(a)};SflWrapper.prototype.currentCursorID=function(){return this.object._sahi_currentCursorID()};
SflWrapper.prototype.addAllMetaData=function(){for(var a=0;a<_sahi.accessors_flex_metadata.length;a++)this.addMetaData(_sahi.accessors_flex_metadata[a]);SflWrapper.prototype.cell=this.getFlexFn("cell");this.addCustomMetaData()};Sahi.prototype.isFlexObj=function(a){try{return a.isSFL}catch(b){return!1}};Sahi.prototype.getFlexWrapper=function(a){return new (this.getWindow(a).SflWrapper)(a)};
Sahi.prototype._flex=function(a){try{var b=this._object(a);if(b&&"function"==typeof b._sahi_getFlexId||(b=this._embed(a))&&"function"==typeof b._sahi_getFlexId)return this.getFlexWrapper(b)}catch(c){return null}};
Sahi.prototype._findFlexElement=function(a,b,c,d){a=a[b](c);if(d&&"dom"==d.type){if("_in"==d.relation)return a.inside(d.element);if("_near"==d.relation)return a.near(d.element);if("_leftOf"==d.relation)return a.leftOf(d.element);if("_rightOf"==d.relation)return a.rightOf(d.element);if("_under"==d.relation)return a.under(d.element)}return a};Sahi.prototype._sfl_executeFn=function(a,b){return a.executeFn.apply(a,this.getArgsAr(arguments,1))};Sahi.prototype._sfl_set=function(a,b,c){return a.set(b,c)};
Sahi.prototype._sfl_get=function(a,b){return a.get(b)};Sahi.prototype._sfl_listProperties=function(a,b){return a.listProperties()};Sahi.prototype._sfl_introspect=function(a){return a.introspect()};Sahi.prototype._sfl_getGridData=function(a,b,c){return a.getGridData(b,c)};Sahi.prototype._sfl_getData=function(a){return a.getData()};Sahi.prototype._f=Sahi.prototype._flex;Sahi.prototype.insideFlex=function(a){this.isInsideFlex=a};
Sahi.prototype.setMyFlexId=function(a){try{var b=this._embed(a)||this._object(a);if(!b)return null;var c=this.isBlankOrNull(b.id)?b.name:b.id;b._sahi_setFlexId(c)}catch(d){alert(d)}};